on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build --configuration Release EpubMaker
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./artifacts EpubMaker
      - name: Get version
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: EpubMaker/EpubMaker.csproj
      - name: Push
        run: dotnet nuget push ./artifacts/Atulin.EpubMaker.${{steps.get-version.outputs.package-version}}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate        
